name: Generate rule set

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `main` branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Corepack
        run: npm i corepack -g && corepack enable

      - name: Install dependencies
        run: pnpm i

      - name: Generate rule set
        run: pnpm generate

      - name: Push new rule set
        run: |
          cd dist
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b dist
          git add .
          git commit -m "update rule set"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin dist

      - name: Flush jsDelivr CDN
        run: curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@dist/adobe-telemetry.yml"
